### ISSUE TITLE
RK the logo is not looking eveident

### ISSUE THREAD

**Issue by Shreyas-sonu** [1999rkgupta/resume#1]
RK color thoda evident karde bhai.. what is this behaviour

![image](https://github.com/1999rkgupta/resume/assets/111351684/9bafb88d-6f65-4986-9d59-a38881866ed7)

**Comment by 1999rkgupta** [comment]
ok bro, i'll change it with new logo

**Comment by Shreyas-sonu** [comment]
tik hai danyabad
